name: CD
run-name: Build and Deploy
on:
  push:
    branches:
      - main
    tags:
      - "dev/*"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Zola
        run: sudo snap install zola --edge

      - name: Build
        run: zola build -o dist/

      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          ARGS: "--delete"
          SOURCE: "dist/"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.TARGET }}